### ISSUE TITLE
Issue and other activity notifications

### ISSUE THREAD

**Issue by yuvilio** [sickill/git-dude#38]
Would issue updates/mentions and the like [activity notifications](https://developer.github.com/v3/activity/notifications/)  be within scope of this script to consider adding or accepting a pull request for? Not sure if it's possible just yet, but thought it would be nice to take that out of the realm of email and into desktop notifications like this does with commits/tags/..

**Comment by sickill** [comment]
This tool is meant to be focused on git, and not any particular hosting / issue tracking / social coding platform, so I'm not really eager to add the features you mentioned to it. But feel free to fork it :)
